// Property test for processing protobuf integration
const fs = require('fs');
const path = require('path');

describe('Processing Protobuf Integration Property Tests', () => {
  // Feature: sdk-protobuf-upgrade, Property 5: Processing Protobuf Integration
  
  test('SGProcessing.ts should exist in data/protobuf/processing/ directory', () => {
    const sgProcessingPath = path.join(__dirname, '../../data/protobuf/processing/SGProcessing.ts');
    expect(fs.existsSync(sgProcessingPath)).toBe(true);
    
    const content = fs.readFileSync(sgProcessingPath, 'utf8');
    
    // Verify it's generated by the correct protobuf-ts version
    expect(content).toMatch(/@generated by protobuf-ts 2\.11\./);
    
    // Verify it imports from @protobuf-ts/runtime
    expect(content).toMatch(/@protobuf-ts\/runtime/);
  });

  test('SGProcessing should export required processing interfaces', () => {
    const sgProcessingPath = path.join(__dirname, '../../data/protobuf/processing/SGProcessing.ts');
    const content = fs.readFileSync(sgProcessingPath, 'utf8');
    
    // Verify key interfaces are exported
    expect(content).toMatch(/export interface Task/);
    expect(content).toMatch(/export interface SubTask/);
    expect(content).toMatch(/export interface TaskResult/);
    expect(content).toMatch(/export interface ProcessingQueue/);
    expect(content).toMatch(/export interface SubTaskResult/);
  });

  test('processing functionality should reference correct protobuf location', () => {
    const sourceFiles = [
      'functions/ipfs/node.ts',
      'functions/messages/processing.ts'
    ];
    
    sourceFiles.forEach(filePath => {
      const fullPath = path.join(__dirname, '../../', filePath);
      
      if (fs.existsSync(fullPath)) {
        const content = fs.readFileSync(fullPath, 'utf8');
        
        // If file mentions SGProcessing, it should reference the correct path
        if (content.includes('SGProcessing')) {
          expect(content).toMatch(/data\/protobuf\/processing\/SGProcessing/);
        }
      }
    });
  });

  test('SGProcessing interfaces should have proper structure', () => {
    const sgProcessingPath = path.join(__dirname, '../../data/protobuf/processing/SGProcessing.ts');
    const content = fs.readFileSync(sgProcessingPath, 'utf8');
    
    // Task interface should have required fields
    expect(content).toMatch(/interface Task[\s\S]*ipfsBlockId.*string/);
    expect(content).toMatch(/interface Task[\s\S]*jsonData.*Uint8Array/);
    expect(content).toMatch(/interface Task[\s\S]*resultsChannel.*string/);
    
    // SubTask interface should have required fields
    expect(content).toMatch(/interface SubTask[\s\S]*ipfsBlockId.*string/);
    expect(content).toMatch(/interface SubTask[\s\S]*chunksToProcess.*ProcessingChunk/);
    
    // TaskResult interface should have required fields
    expect(content).toMatch(/interface TaskResult[\s\S]*subtaskResults.*SubTaskResult/);
  });

  test('processing protobuf should be compatible with new runtime', () => {
    const sgProcessingPath = path.join(__dirname, '../../data/protobuf/processing/SGProcessing.ts');
    const content = fs.readFileSync(sgProcessingPath, 'utf8');
    
    // Should use new runtime imports
    expect(content).toMatch(/import.*from "@protobuf-ts\/runtime"/);
    
    // Should have MessageType exports
    expect(content).toMatch(/MessageType/);
    
    // Should not have old protobuf-ts patterns
    expect(content).not.toMatch(/@protobuf-ts\/runtime@2\.9/);
  });

  test('processing directory structure should be correct', () => {
    const processingDir = path.join(__dirname, '../../data/protobuf/processing');
    
    // Directory should exist
    expect(fs.existsSync(processingDir)).toBe(true);
    
    // Should be a directory
    const stats = fs.statSync(processingDir);
    expect(stats.isDirectory()).toBe(true);
    
    // Should contain SGProcessing.ts
    const files = fs.readdirSync(processingDir);
    expect(files).toContain('SGProcessing.ts');
  });
});