// Property test for protobuf file compatibility
const fs = require('fs');
const path = require('path');

describe('Protobuf File Compatibility Property Tests', () => {
  // Feature: sdk-protobuf-upgrade, Property 1: Protobuf File Compatibility
  test('all protobuf TypeScript files should compile with new runtime', () => {
    const protobufDir = path.join(__dirname, '../../data/protobuf');
    
    // Get all .ts files in protobuf directory recursively
    const getProtobufFiles = (dir) => {
      const files = [];
      const items = fs.readdirSync(dir);
      
      for (const item of items) {
        const fullPath = path.join(dir, item);
        const stat = fs.statSync(fullPath);
        
        if (stat.isDirectory()) {
          files.push(...getProtobufFiles(fullPath));
        } else if (item.endsWith('.ts')) {
          files.push(fullPath);
        }
      }
      
      return files;
    };
    
    const protobufFiles = getProtobufFiles(protobufDir);
    expect(protobufFiles.length).toBeGreaterThan(0);
    
    // For each protobuf file, verify it has the expected structure
    protobufFiles.forEach(filePath => {
      const content = fs.readFileSync(filePath, 'utf8');
      
      // Check that file is generated by protobuf-ts
      expect(content).toMatch(/@generated by protobuf-ts/);
      
      // Check that it imports from @protobuf-ts/runtime (new runtime)
      expect(content).toMatch(/@protobuf-ts\/runtime/);
      
      // Check that it has proper TypeScript interface exports
      expect(content).toMatch(/export interface/);
      
      // Verify no syntax errors by checking basic structure
      expect(content).toMatch(/import.*from/);
    });
  });

  test('new CRDT protobuf files should be present and properly structured', () => {
    const crdtDir = path.join(__dirname, '../../data/protobuf/crdt');
    
    // Check that CRDT directory exists
    expect(fs.existsSync(crdtDir)).toBe(true);
    
    // Check required CRDT files exist
    const requiredFiles = ['bcast.ts', 'delta.ts', 'heads.ts'];
    
    requiredFiles.forEach(fileName => {
      const filePath = path.join(crdtDir, fileName);
      expect(fs.existsSync(filePath)).toBe(true);
      
      const content = fs.readFileSync(filePath, 'utf8');
      
      // Verify it's generated by the new protobuf-ts version
      expect(content).toMatch(/@generated by protobuf-ts 2\.11\./);
      
      // Verify it has proper exports
      expect(content).toMatch(/export interface/);
    });
  });

  test('processing protobuf files should be present and compatible', () => {
    const processingDir = path.join(__dirname, '../../data/protobuf/processing');
    
    // Check that processing directory exists
    expect(fs.existsSync(processingDir)).toBe(true);
    
    // Check SGProcessing.ts exists
    const sgProcessingPath = path.join(processingDir, 'SGProcessing.ts');
    expect(fs.existsSync(sgProcessingPath)).toBe(true);
    
    const content = fs.readFileSync(sgProcessingPath, 'utf8');
    
    // Verify it's properly generated
    expect(content).toMatch(/@generated by protobuf-ts/);
    expect(content).toMatch(/export interface/);
    expect(content).toMatch(/@protobuf-ts\/runtime/);
  });
});